mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('createPoll/', views.create, name='create'),
    path('creating/', views.create_poll,name='create_poll')
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.template import loader
from .models import Question
from django.shortcuts import get_object_or_404,render
from django.views import generic
from django.urls import reverse
from django.utils import timezone

from .models import Choice, Question

choices = []
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def create(request):
    choices = ['','','']
    return render(request, 'polls/create.html', {'choices': choices})

def create_poll(request):
    q = Question(question_text=request.POST['question'], pub_date=timezone.now())
    q.save()
    c=Question.objects.get(pk=q.id)
    data = request.POST
    choice_list = data.getlist('choice')
    
    for i in choice_list:
        c.choice_set.create(choice_text=i, votes=0)
    # c.choice_set.create(choice_text=request.POST['choice1'], votes=0)
    # c.choice_set.create(choice_text=request.POST['choice2'], votes=0)
    # c.choice_set.create(choice_text=request.POST['choice3'], votes=0)
    c.save()
    return HttpResponseRedirect(reverse('polls:index'))

polls/templates/polls/create.html
<!DOCTYPE html>
<html lang="en">



<body>
    <form action="{% url 'polls:create_poll' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>Create a Poll</h1>
            </legend>
            Question :
            <input type="text" name="question" id="questionId">
            <br>
            <br>
            Polls:
            <input type="button" value="Add" id="add">
            <br>
            <br>
            <div class="choice" name="'choices">
                
            </div>
            <!-- {% for choice in choices %}
            {{ forloop.counter }}. <input type="text" id="choice{{ forloop.counter }}" name="choice{{ forloop.counter }}" value="{{ choice }}">
            <br>
            <br>
            {% endfor %} -->
        </fieldset>
        <br>
        <input type="submit" value="create">
    </form>
</body>

<head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript">
        let val = 1;
        $("#add").click(function () {
            $('.choice').append(`${val}. <input type="text" name="choice"><br><br>`)
            val++;
        });
    </script>
</head>

</html>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{ question.question_text }}</h1>
        </legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>
<div class="container">
    <div class="row">
        <div class="col-10">
            {% if latest_question_list %}
            <ul>
                {% for question in latest_question_list %}
                <li><a href={% url 'polls:detail' question.id %}>{{ question.question_text }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <p>No polls are available.</p>
            {% endif %}
        </div>
        <div class="col-2">
            <br>
            <button class="btn btn-primary btn-sm" onclick="location.href='{% url 'polls:create' %}'">Create a
                Poll</button>
        </div>
    </div>
</div>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>